fix(extra/python3-colcon-common-extensions): remove load-limting option
problem:
    By default colcon-cmake tries to build with load-averaging using
    `make -l` (far enough under the hood) which leads to very verbose
    build logs complaining that "gmake[1]: cannot enforce load limit:
    getloadavg: Function not implemented". There isn't much to it beyond
    that our libc does not implement `getloadavg` so we dont support
    `-l` option for builds.

Solution:
    By the small sliver of chance that we end up supporting this function
    down the line, try except os.getloadavg. If AttributeError is thrown
    skip returning `f'-l{jobs}'.

    In order to apply 0000-colcon-cmake-getloadavg.patch I added
    prepare() which includes _apply_qnx_patch(); this was stolen from
    our exisiting ros packages in order to maintain consistency with how
    we apply patches in metapkges